pipeline{
    agent any
    environment{
        DATABASE_URI = credentials("DATABASE_URI")
        app_version = 'v1'
        rollback = 'false'
    }
    stages{
        stage("Testing"){
            steps{
                sh "bash jenkins/test.sh"
            }
        }
        stage("Build & Push"){
            steps{
                sh "docker-compose build --parallel && docker-compose push"
            }
        }
        stage("Config Management (ansible)"){
            steps{
                sh "cd ansible && /home/jenkins/.local/bin/ansible-playbook -i inventory playbook.yaml"
            }
        }
        stage("Deploy"){
            steps{
                sh "bash jenkins/deploy.sh"
            }
        }
    }
    post{
        always{
            junit "**/junit.xml"
            cobertura coberturaReportFile: '**/coverage.xml', failNoReports: false, failUnstable: false, onlyStable: false
        }
    }
}